name: mqtt_client_example
description: Demonstrates how to use mqtt_client with flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  crypto: ^2.0.6
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  mqtt_client: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
